# Generated by Django 3.2.12 on 2022-05-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_commentarticle_date'),
        ('accounts', '0005_alter_experience_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='article.Tag'),
        ),
    ]
