# Generated by Django 3.2.12 on 2022-05-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_experience_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='experience',
            unique_together=set(),
        ),
    ]
