# Generated by Django 4.0.2 on 2022-04-28 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_rename_usr_article_user_relationarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationarticle',
            name='reaction',
            field=models.CharField(choices=[('nothing', 'nothing'), ('dislike', 'dislike'), ('like', 'like')], default='nothing', max_length=100),
        ),
        migrations.CreateModel(
            name='CommentArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(blank=True, max_length=1000, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
