# Generated by Django 4.0.2 on 2022-04-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_commentarticle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
