# Generated by Django 3.2.12 on 2022-05-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_question_tags_question_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=1000)),
                ('output', models.CharField(max_length=1000)),
                ('explaination', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques', to='question.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='example',
            field=models.ManyToManyField(blank=True, related_name='exampleQuestion', to='question.Example'),
        ),
    ]
