# Generated by Django 3.2.12 on 2022-05-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20220509_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('ar', 'ar'), ('dp', 'Dynamic Programing')], max_length=2, null=True),
        ),
    ]
