# Generated by Django 3.2.12 on 2022-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('Arr', 'Array'), ('DP', 'Dynamic Programing'), ('STR', 'String'), ('LL', 'Linked List'), ('S', 'Stack')], max_length=3, null=True),
        ),
    ]
