# Generated by Django 3.2.12 on 2022-05-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='img',
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=100),
        ),
    ]
