# Generated by Django 3.2.12 on 2022-05-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20220513_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
