# Generated by Django 3.2.12 on 2022-05-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_unit_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='units', to='notes.Unit'),
        ),
    ]
