# Generated by Django 3.2.12 on 2022-05-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_subject_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('unitNo', 'subject')},
        ),
    ]
