# Generated by Django 3.2.12 on 2022-05-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_subject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unitNo']},
        ),
    ]
