# Generated by Django 3.2.12 on 2022-05-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='start_date',
        ),
        migrations.AddField(
            model_name='test',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
