# Generated by Django 3.2.12 on 2022-05-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testroom', '0002_auto_20220530_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='entries',
            field=models.ManyToManyField(blank=True, to='testroom.TestCase'),
        ),
    ]
