# Generated by Django 3.2.12 on 2022-05-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testroom', '0003_test_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
