# Generated by Django 4.0.2 on 2022-04-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0002_doubt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
