# Generated by Django 4.0.2 on 2022-04-29 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doubt', '0003_doubt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='subComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubt.doubt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('doubt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doubt.doubt')),
                ('subComment', models.ManyToManyField(blank=True, to='doubt.subComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='doubt',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='doubt.Comment'),
        ),
    ]
