# Generated by Django 4.0.2 on 2022-04-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0004_subcomment_comment_doubt_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='heading',
        ),
    ]
