# Generated by Django 3.2.12 on 2022-05-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0005_remove_comment_heading_remove_subcomment_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
