# Generated by Django 3.2.12 on 2022-05-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_remove_question_image'),
        ('doubt', '0007_doubt_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.category'),
        ),
    ]
