# Generated by Django 3.2.12 on 2022-05-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubt', '0008_doubt_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubt',
            name='image',
        ),
    ]
